import type { Play, Drill, PracticePlan, Team, Game, Player } from "@/types";

const createPlayer = (id: string, name: string, number: number, position: string): Player => ({
  id, name, number, position,
});

export const varsityPlayers: Player[] = [
  createPlayer("p1", "Marcus Johnson", 1, "PG"),
  createPlayer("p2", "Devon Williams", 3, "SG"),
  createPlayer("p3", "Tyler Brown", 5, "SF"),
  createPlayer("p4", "Andre Davis", 10, "PF"),
  createPlayer("p5", "Chris Martin", 15, "C"),
  createPlayer("p6", "James Wilson", 2, "PG"),
  createPlayer("p7", "Kyle Thomas", 11, "SG"),
  createPlayer("p8", "Eric Anderson", 22, "SF"),
  createPlayer("p9", "Daniel Lee", 33, "PF"),
  createPlayer("p10", "Mike Robinson", 44, "C"),
  createPlayer("p11", "Noah Garcia", 4, "SG"),
  createPlayer("p12", "Sam Martinez", 24, "SF"),
];

export const awayPlayers: Player[] = [
  createPlayer("a1", "Ryan Cooper", 0, "PG"),
  createPlayer("a2", "Blake Foster", 7, "SG"),
  createPlayer("a3", "Jordan Hayes", 12, "SF"),
  createPlayer("a4", "Trevor Scott", 21, "PF"),
  createPlayer("a5", "Malik Turner", 34, "C"),
  createPlayer("a6", "Isaiah Price", 3, "PG"),
  createPlayer("a7", "Cameron Reed", 14, "SG"),
  createPlayer("a8", "Austin Brooks", 25, "SF"),
  createPlayer("a9", "Logan Wright", 30, "PF"),
  createPlayer("a10", "Ethan Hall", 42, "C"),
];

export const plays: Play[] = [
  {
    id: "play-1",
    name: "High Pick and Roll",
    type: "offense",
    tags: ["Pick & Roll", "Motion", "Guard"],
    description: "Classic high ball screen action with multiple reads for the ball handler and roll man.",
    steps: [
      {
        id: "s1",
        description: "Point guard brings ball up, big sets up at top of key",
        positions: [
          { id: "1", x: 200, y: 380, label: "1" },
          { id: "2", x: 310, y: 340, label: "2" },
          { id: "3", x: 90, y: 340, label: "3" },
          { id: "4", x: 200, y: 260, label: "4" },
          { id: "5", x: 200, y: 120, label: "5" },
        ],
        arrows: [],
      },
      {
        id: "s2",
        description: "Big comes up to set ball screen, guard drives left",
        positions: [
          { id: "1", x: 140, y: 320, label: "1" },
          { id: "2", x: 310, y: 340, label: "2" },
          { id: "3", x: 90, y: 340, label: "3" },
          { id: "4", x: 180, y: 320, label: "4" },
          { id: "5", x: 200, y: 120, label: "5" },
        ],
        arrows: [
          { id: "a1", fromX: 200, fromY: 380, toX: 140, toY: 320, type: "dribble" },
          { id: "a2", fromX: 200, fromY: 260, toX: 180, toY: 320, type: "cut" },
        ],
      },
      {
        id: "s3",
        description: "Big rolls to basket, guard reads defense for pass or drive",
        positions: [
          { id: "1", x: 100, y: 280, label: "1" },
          { id: "2", x: 310, y: 340, label: "2" },
          { id: "3", x: 90, y: 340, label: "3" },
          { id: "4", x: 200, y: 140, label: "4" },
          { id: "5", x: 200, y: 120, label: "5" },
        ],
        arrows: [
          { id: "a3", fromX: 180, fromY: 320, toX: 200, toY: 140, type: "cut" },
          { id: "a4", fromX: 100, fromY: 280, toX: 200, toY: 140, type: "pass" },
        ],
      },
    ],
    isFavorite: true,
    createdAt: "2026-01-15",
  },
  {
    id: "play-2",
    name: "Flex Offense",
    type: "offense",
    tags: ["Motion", "Screening", "Continuity"],
    description: "Continuity offense built on down screens and baseline cuts with constant player movement.",
    steps: [
      {
        id: "s1",
        description: "Initial setup in flex alignment",
        positions: [
          { id: "1", x: 200, y: 380, label: "1" },
          { id: "2", x: 320, y: 300, label: "2" },
          { id: "3", x: 80, y: 300, label: "3" },
          { id: "4", x: 120, y: 160, label: "4" },
          { id: "5", x: 280, y: 160, label: "5" },
        ],
        arrows: [],
      },
    ],
    isFavorite: false,
    createdAt: "2026-01-20",
  },
  {
    id: "play-3",
    name: "1-3-1 Zone Trap",
    type: "defense",
    tags: ["Zone", "Trapping", "Press"],
    description: "Aggressive 1-3-1 zone designed to create turnovers through trapping on the sidelines.",
    steps: [
      {
        id: "s1",
        description: "Initial 1-3-1 zone alignment",
        positions: [
          { id: "1", x: 200, y: 360, label: "1" },
          { id: "2", x: 100, y: 280, label: "2" },
          { id: "3", x: 200, y: 280, label: "3" },
          { id: "4", x: 300, y: 280, label: "4" },
          { id: "5", x: 200, y: 140, label: "5" },
        ],
        arrows: [],
      },
    ],
    isFavorite: true,
    createdAt: "2026-02-01",
  },
  {
    id: "play-4",
    name: "Horns Set",
    type: "offense",
    tags: ["Set Play", "Post", "Pick & Roll"],
    description: "Two bigs start at elbows, multiple options for ball screen or post entry.",
    steps: [
      {
        id: "s1",
        description: "Horns alignment with bigs at elbows",
        positions: [
          { id: "1", x: 200, y: 380, label: "1" },
          { id: "2", x: 330, y: 350, label: "2" },
          { id: "3", x: 70, y: 350, label: "3" },
          { id: "4", x: 140, y: 240, label: "4" },
          { id: "5", x: 260, y: 240, label: "5" },
        ],
        arrows: [],
      },
    ],
    isFavorite: false,
    createdAt: "2026-02-05",
  },
  {
    id: "play-5",
    name: "Box Out of Bounds",
    type: "special",
    tags: ["SLOB", "Inbounds", "Quick Hitter"],
    description: "Sideline out of bounds play from box set with back screen and flare screen options.",
    steps: [
      {
        id: "s1",
        description: "Box alignment on sideline",
        positions: [
          { id: "1", x: 50, y: 240, label: "1" },
          { id: "2", x: 160, y: 200, label: "2" },
          { id: "3", x: 240, y: 200, label: "3" },
          { id: "4", x: 160, y: 140, label: "4" },
          { id: "5", x: 240, y: 140, label: "5" },
        ],
        arrows: [],
      },
    ],
    isFavorite: false,
    createdAt: "2026-02-10",
  },
  {
    id: "play-6",
    name: "Motion Weak",
    type: "offense",
    tags: ["Motion", "Weak Side", "Cutting"],
    description: "Motion offense emphasizing weak-side action with UCLA cuts and pin downs.",
    steps: [
      {
        id: "s1",
        description: "Initial motion weak setup",
        positions: [
          { id: "1", x: 200, y: 380, label: "1" },
          { id: "2", x: 320, y: 320, label: "2" },
          { id: "3", x: 80, y: 320, label: "3" },
          { id: "4", x: 100, y: 180, label: "4" },
          { id: "5", x: 300, y: 180, label: "5" },
        ],
        arrows: [],
      },
    ],
    isFavorite: true,
    createdAt: "2026-02-12",
  },
  {
    id: "double-ball-screen",
    name: "Double ball screen",
    type: "offense",
    tags: ["Pick & Roll", "Ball Screen", "Guard"],
    description:
      "Guard comes off two consecutive ball screens from the bigs at the top of the key. First screen from 4, second from 5; read the defense for drive, pull-up, or kick to roll man.",
    steps: [
      {
        id: "dbs-s1",
        description: "Setup: guard at top, bigs at elbows, wings spaced",
        positions: [
          { id: "1", x: 200, y: 360, label: "1" },
          { id: "2", x: 320, y: 300, label: "2" },
          { id: "3", x: 80, y: 300, label: "3" },
          { id: "4", x: 160, y: 220, label: "4" },
          { id: "5", x: 240, y: 220, label: "5" },
        ],
        arrows: [],
      },
      {
        id: "dbs-s2",
        description: "4 sets first ball screen; 1 dribbles left off the screen",
        positions: [
          { id: "1", x: 120, y: 280, label: "1" },
          { id: "2", x: 320, y: 300, label: "2" },
          { id: "3", x: 80, y: 300, label: "3" },
          { id: "4", x: 180, y: 260, label: "4" },
          { id: "5", x: 240, y: 220, label: "5" },
        ],
        arrows: [
          { id: "dbs-a1", fromX: 200, fromY: 360, toX: 120, toY: 280, type: "dribble" },
          { id: "dbs-sr1", fromX: 160, fromY: 220, toX: 180, toY: 260, type: "screen" },
        ],
      },
      {
        id: "dbs-s3",
        description: "5 sets second ball screen; 1 continues left off both screens",
        positions: [
          { id: "1", x: 80, y: 220, label: "1" },
          { id: "2", x: 320, y: 300, label: "2" },
          { id: "3", x: 80, y: 300, label: "3" },
          { id: "4", x: 160, y: 180, label: "4" },
          { id: "5", x: 200, y: 240, label: "5" },
        ],
        arrows: [
          { id: "dbs-a2", fromX: 120, fromY: 280, toX: 80, toY: 220, type: "dribble" },
          { id: "dbs-sr2", fromX: 240, fromY: 220, toX: 200, toY: 240, type: "screen" },
          { id: "dbs-c1", fromX: 180, fromY: 260, toX: 160, toY: 180, type: "cut" },
        ],
      },
      {
        id: "dbs-s4",
        description: "1 attacks the lane; 4 rolls to the basket",
        positions: [
          { id: "1", x: 140, y: 160, label: "1" },
          { id: "2", x: 320, y: 300, label: "2" },
          { id: "3", x: 80, y: 300, label: "3" },
          { id: "4", x: 200, y: 100, label: "4" },
          { id: "5", x: 200, y: 240, label: "5" },
        ],
        arrows: [
          { id: "dbs-a3", fromX: 80, fromY: 220, toX: 140, toY: 160, type: "dribble" },
          { id: "dbs-c2", fromX: 160, fromY: 180, toX: 200, toY: 100, type: "cut" },
          { id: "dbs-p1", fromX: 140, fromY: 160, toX: 200, toY: 100, type: "pass" },
        ],
      },
      {
        id: "dbs-s5",
        description: "Finish: 4 at the rim; 1 can kick to 2 or 3 if help comes",
        positions: [
          { id: "1", x: 160, y: 140, label: "1" },
          { id: "2", x: 320, y: 300, label: "2" },
          { id: "3", x: 80, y: 300, label: "3" },
          { id: "4", x: 200, y: 60, label: "4" },
          { id: "5", x: 200, y: 220, label: "5" },
        ],
        arrows: [
          { id: "dbs-p2", fromX: 140, fromY: 160, toX: 200, toY: 60, type: "pass" },
        ],
      },
    ],
    isFavorite: false,
    createdAt: "2026-02-26",
  },
];

export const drills: Drill[] = [
  {
    id: "drill-1",
    name: "Three-Man Weave",
    category: "passing",
    level: "beginner",
    tags: ["Passing", "Beginner"],
    description: "Players fill 3 lanes and weave pass up court. Great for conditioning and passing accuracy.",
    duration: 10,
    coachingCues: [
      "Lead the receiver with the pass",
      "Sprint to the opposite lane after passing",
      "Finish with a layup on each rep",
      "Call out receiver's name before passing",
    ],
    progressions: [
      { level: "Basic", description: "Standard three-man weave with chest passes" },
      { level: "Advanced", description: "Add bounce passes and behind-the-back passes" },
      { level: "Competition", description: "Race against another group, no turnovers" },
    ],
    isFavorite: true,
    createdAt: "2026-01-10",
    playerCount: "6+",
  },
  {
    id: "drill-2",
    name: "Mikan Drill",
    category: "shooting",
    level: "beginner",
    tags: ["Shooting", "Beginner"],
    description: "Close-range finishing drill alternating layups on each side of the basket.",
    duration: 5,
    coachingCues: [
      "Use the backboard on every shot",
      "Alternate hands on each side",
      "Keep the ball high — don't bring it below your chin",
      "Quick feet, quick hands",
    ],
    progressions: [
      { level: "Basic", description: "Standard right-left alternating layups" },
      { level: "Reverse", description: "Add reverse layups on each side" },
      { level: "Power", description: "Two-foot power finish variation" },
    ],
    isFavorite: false,
    createdAt: "2026-01-12",
  },
  {
    id: "drill-3",
    name: "Shell Drill",
    category: "defense",
    level: "intermediate",
    tags: ["Defense", "Team Defense"],
    description: "4-on-4 shell defensive drill working on help-side positioning and closeouts.",
    duration: 12,
    coachingCues: [
      "Jump to the ball on every pass",
      "Ball-you-man triangle positioning",
      "Active hands in passing lanes",
      "Communicate on every screen",
    ],
    progressions: [
      { level: "Walk-through", description: "Offense passes only, no dribble" },
      { level: "Live", description: "Add one dribble per catch" },
      { level: "Full", description: "Full live play with screens" },
    ],
    isFavorite: true,
    createdAt: "2026-01-18",
    playerCount: "8",
  },
  {
    id: "drill-4",
    name: "Spot Shooting",
    category: "shooting",
    level: "intermediate",
    tags: ["Shooting", "Spot Shooting"],
    description: "Hit shots from 5 designated spots around the arc. Track makes vs. attempts.",
    duration: 15,
    coachingCues: [
      "Feet set before the catch",
      "Sweep and go on misses",
      "Follow your shot for offensive rebounds",
      "Game speed catch-and-shoot rhythm",
    ],
    progressions: [
      { level: "Stationary", description: "Catch and shoot from each spot" },
      { level: "Movement", description: "Relocate between spots off screens" },
      { level: "Contested", description: "Add a closeout defender" },
    ],
    isFavorite: false,
    createdAt: "2026-01-25",
  },
  {
    id: "drill-5",
    name: "Defensive Slides",
    category: "defense",
    level: "beginner",
    tags: ["Defense", "Footwork"],
    description: "Lateral sliding drill for defensive positioning. Use cones or lines on the court.",
    duration: 8,
    coachingCues: [
      "Stay low — butt down, chest up",
      "Never cross your feet",
      "Push off the trailing foot",
      "Keep active hands at all times",
    ],
    progressions: [
      { level: "Basic", description: "Slide baseline to baseline" },
      { level: "Zig-zag", description: "Add direction changes at cones" },
      { level: "Reaction", description: "React to coach's hand signals" },
    ],
    isFavorite: false,
    createdAt: "2026-02-01",
  },
  {
    id: "drill-6",
    name: "1-on-1 Full Court",
    category: "dribbling",
    level: "advanced",
    tags: ["Dribbling", "1-on-1"],
    description: "Full court 1-on-1 live play. Offensive player works on moves, defender on containment.",
    duration: 10,
    coachingCues: [
      "Attack the defender's front hip",
      "Change pace before changing direction",
      "Defender: stay between ball and basket",
      "Finish at the rim through contact",
    ],
    progressions: [
      { level: "Half Court", description: "Start at half court" },
      { level: "Full Court", description: "Start from baseline to baseline" },
      { level: "Advantage", description: "Add trail defender for 1-on-2 transition" },
    ],
    isFavorite: false,
    createdAt: "2026-02-05",
    playerCount: "2+",
  },
  {
    id: "drill-7",
    name: "Passing Progression",
    category: "passing",
    level: "intermediate",
    tags: ["Passing", "Fundamentals"],
    description: "Progressive passing drill from stationary to on-the-move with different pass types.",
    duration: 10,
    coachingCues: [
      "Step into every pass",
      "Snap the wrists on chest passes",
      "Bounce pass target: receiver's hip",
      "Eyes up — see the floor",
    ],
    progressions: [
      { level: "Stationary", description: "Partner passing — chest, bounce, overhead" },
      { level: "Moving", description: "Pass while jogging up court" },
      { level: "Pressure", description: "Add a defender in the passing lane" },
    ],
    isFavorite: false,
    createdAt: "2026-02-08",
    playerCount: "2+",
  },
  {
    id: "drill-8",
    name: "Box Out Drill",
    category: "rebounding",
    level: "beginner",
    tags: ["Rebounding", "Fundamentals"],
    description: "Practice proper box-out technique and rebounding fundamentals.",
    duration: 10,
    coachingCues: [
      "Make contact — feel the offensive player",
      "Wide base, low center of gravity",
      "Chin the ball after securing rebound",
      "Outlet pass within 2 seconds",
    ],
    progressions: [
      { level: "No ball", description: "Practice box-out positioning only" },
      { level: "With shot", description: "Coach shoots, players box out and rebound" },
      { level: "Live", description: "2-on-2 rebounding with live play after" },
    ],
    isFavorite: false,
    createdAt: "2026-02-10",
    playerCount: "4+",
  },
];

export const teams: Team[] = [
  {
    id: "team-1",
    name: "Varsity Tigers",
    record: { wins: 14, losses: 3 },
    players: varsityPlayers,
    playbook: ["play-1", "play-2", "play-3", "play-4"],
  },
  {
    id: "team-2",
    name: "New York Knicks",
    record: { wins: 8, losses: 9 },
    players: awayPlayers,
    playbook: ["play-1", "play-5", "play-6"],
  },
];

export const practicePlans: PracticePlan[] = [
  {
    id: "pp-1",
    name: "Tuesday Practice",
    teamId: "team-1",
    date: "2026-02-24",
    totalDuration: 100,
    blocks: [
      { id: "b1", name: "Dynamic Warm-up", description: "Light jogging and stretching", type: "warmup", duration: 10 },
      { id: "b2", name: "Three-Man Weave", description: "Passing and conditioning", type: "skill", duration: 15, drillId: "drill-1" },
      { id: "b3", name: "High Pick and Roll", description: "Offensive set practice", type: "team", duration: 20, playId: "play-1" },
      { id: "b4", name: "Shell Drill", description: "Defensive positioning", type: "skill", duration: 15, drillId: "drill-3" },
      { id: "b5", name: "5-on-5 Scrimmage", description: "Full court game", type: "situational", duration: 30 },
      { id: "b6", name: "Cool Down", description: "Stretching and review", type: "cooldown", duration: 10 },
    ],
  },
];

export const games: Game[] = [
  {
    id: "game-1",
    homeTeam: "Varsity Tigers",
    awayTeam: "Warriors",
    homeScore: 45,
    awayScore: 42,
    status: "live",
    quarter: 3,
    date: "2026-02-23",
    events: [
      { id: "e1", timestamp: "Q3 4:32", quarter: 3, playerId: "p1", playerName: "M. Johnson", team: "home", action: "2PT Made", points: 2 },
      { id: "e2", timestamp: "Q3 4:15", quarter: 3, playerId: "a2", playerName: "B. Foster", team: "away", action: "3PT Missed" },
      { id: "e3", timestamp: "Q3 3:58", quarter: 3, playerId: "p4", playerName: "A. Davis", team: "home", action: "Rebound" },
      { id: "e4", timestamp: "Q3 3:45", quarter: 3, playerId: "p2", playerName: "D. Williams", team: "home", action: "3PT Made", points: 3 },
      { id: "e5", timestamp: "Q3 3:20", quarter: 3, playerId: "a1", playerName: "R. Cooper", team: "away", action: "2PT Made", points: 2 },
    ],
    homeRoster: varsityPlayers,
    awayRoster: awayPlayers,
  },
  {
    id: "game-2",
    homeTeam: "Varsity Tigers",
    awayTeam: "Eagles",
    homeScore: 78,
    awayScore: 72,
    status: "final",
    quarter: 4,
    date: "2026-02-19",
    events: [],
    homeRoster: varsityPlayers,
    awayRoster: [],
  },
  {
    id: "game-3",
    homeTeam: "Varsity Tigers",
    awayTeam: "Bulldogs",
    homeScore: 0,
    awayScore: 0,
    status: "upcoming",
    quarter: 0,
    date: "2026-02-24",
    time: "7:00 PM",
    events: [],
    homeRoster: varsityPlayers,
    awayRoster: [],
  },
];

export const tagColors: Record<string, string> = {
  "Pick & Roll": "bg-pb-orange/20 text-pb-orange",
  "Motion": "bg-pb-blue/20 text-pb-blue",
  "Guard": "bg-emerald-500/20 text-emerald-400",
  "Screening": "bg-amber-500/20 text-amber-400",
  "Continuity": "bg-purple-500/20 text-purple-400",
  "Zone": "bg-red-500/20 text-red-400",
  "Trapping": "bg-rose-500/20 text-rose-400",
  "Press": "bg-pink-500/20 text-pink-400",
  "Set Play": "bg-indigo-500/20 text-indigo-400",
  "Post": "bg-teal-500/20 text-teal-400",
  "SLOB": "bg-cyan-500/20 text-cyan-400",
  "Inbounds": "bg-sky-500/20 text-sky-400",
  "Quick Hitter": "bg-lime-500/20 text-lime-400",
  "Weak Side": "bg-violet-500/20 text-violet-400",
  "Cutting": "bg-fuchsia-500/20 text-fuchsia-400",
  "Passing": "bg-pb-orange/20 text-pb-orange",
  "Beginner": "bg-emerald-500/20 text-emerald-400",
  "Shooting": "bg-pb-blue/20 text-pb-blue",
  "Defense": "bg-red-500/20 text-red-400",
  "Team Defense": "bg-rose-500/20 text-rose-400",
  "Spot Shooting": "bg-amber-500/20 text-amber-400",
  "Footwork": "bg-purple-500/20 text-purple-400",
  "Dribbling": "bg-cyan-500/20 text-cyan-400",
  "1-on-1": "bg-pink-500/20 text-pink-400",
  "Fundamentals": "bg-teal-500/20 text-teal-400",
  "Rebounding": "bg-indigo-500/20 text-indigo-400",
  "Intermediate": "bg-amber-500/20 text-amber-400",
  "Advanced": "bg-red-500/20 text-red-400",
};
